// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddArtist(arg1:string):Promise<boolean>;

export function Close():Promise<void>;

export function GetArtistsFromDB():Promise<Array<database.Artist>>;

export function RemoveArtist(arg1:string):Promise<boolean>;
