// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Download(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<boolean>;

export function Startup(arg1:context.Context,arg2:boolean):Promise<void>;
