// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['spotdl']['Downloader']['Download'](arg1, arg2, arg3, arg4, arg5);
}

export function Startup(arg1) {
  return window['go']['spotdl']['Downloader']['Startup'](arg1);
}
