// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanUp():Promise<void>;

export function GetDominantColor(arg1:string):Promise<Array<string>>;
