// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanUp() {
  return window['go']['utils']['Utils']['CleanUp']();
}

export function GetDominantColor(arg1) {
  return window['go']['utils']['Utils']['GetDominantColor'](arg1);
}
