// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Disable() {
  return window['go']['autostart']['AutoStart']['Disable']();
}

export function Enable() {
  return window['go']['autostart']['AutoStart']['Enable']();
}

export function IsEnabled() {
  return window['go']['autostart']['AutoStart']['IsEnabled']();
}
