// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function GetAlbum(arg1) {
  return window['go']['main']['App']['GetAlbum'](arg1);
}

export function GetArtist(arg1) {
  return window['go']['main']['App']['GetArtist'](arg1);
}

export function GetDominantColor(arg1) {
  return window['go']['main']['App']['GetDominantColor'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
