// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory():Promise<string>;

export function GetAlbum(arg1:string):Promise<Record<string, any>>;

export function GetArtist(arg1:string):Promise<Record<string, any>>;

export function GetDominantColor(arg1:string):Promise<Array<string>>;

export function Search(arg1:string):Promise<Record<string, any>>;
