// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddArtist(arg1:string):Promise<boolean>;

export function CheckForUpdates():Promise<Record<string, any>>;

export function ChooseDirectory():Promise<string>;

export function Close():Promise<void>;

export function GetAlbum(arg1:string):Promise<Record<string, any>>;

export function GetArtist(arg1:string):Promise<Record<string, any>>;

export function GetArtistsFromDB():Promise<Array<database.Artist>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetTrack(arg1:string):Promise<Record<string, any>>;

export function HasValidSpotifyCredentials():Promise<boolean>;

export function IsANewRelease(arg1:string,arg2:Record<string, any>):Promise<boolean>;

export function RemoveArtist(arg1:string):Promise<boolean>;

export function Search(arg1:string):Promise<Record<string, any>>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;

export function ValidateAndStoreSpotifyCredentials(arg1:string,arg2:string):Promise<boolean>;
