// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddArtist(arg1) {
  return window['go']['main']['App']['AddArtist'](arg1);
}

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function GetAlbum(arg1) {
  return window['go']['main']['App']['GetAlbum'](arg1);
}

export function GetArtist(arg1) {
  return window['go']['main']['App']['GetArtist'](arg1);
}

export function GetArtistsFromDB() {
  return window['go']['main']['App']['GetArtistsFromDB']();
}

export function GetTrack(arg1) {
  return window['go']['main']['App']['GetTrack'](arg1);
}

export function IsANewRelease(arg1, arg2) {
  return window['go']['main']['App']['IsANewRelease'](arg1, arg2);
}

export function RemoveArtist(arg1) {
  return window['go']['main']['App']['RemoveArtist'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}
